// 数据质量升级脚本：为模板山重写 whenToGo / howToGetThere / faqs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = join(__dirname, "..", "src", "data", "mountains-data.json");
const data = JSON.parse(readFileSync(dataPath, "utf-8"));

const UPGRADES = {
  wutaishan: {
    whenToGo:
      "May to September is the main pilgrimage season. May-June brings the clearest skies and the famous aerial views from the Five Terrace peaks, with temperatures 5-20 C and wildflowers covering the high plateau. July-August is warmest (10-25 C) but wetter, with afternoon thunderstorms common above 2,500m and peak domestic crowds around the temples. September-October offers crisp air, golden meadows, and fewer pilgrims — the best balance for photography and the Dai Luoding 'mini-circuit'. Winter (November-March) is brutally cold (-20 C at the summits) and most bus routes between terraces close, but the snow-covered temples at Taihuai town are hauntingly beautiful. Avoid the week around the Lunar New Year and summer school holidays if you want quiet temple visits.",
    howToGetThere:
      "By Air: Fly to Taiyuan Wusu International Airport (TYN), the main gateway for Shanxi. From the airport, take a direct bus or taxi to Taihuai Town (about 3.5-4 hours, roughly CNY 150-200). By High-Speed Train: The nearest high-speed rail station is Xinzhou West on the Beijing-Taiyuan line. From Xinzhou West, buses to Wutai Mountain depart regularly (2-2.5 hours, CNY 80-100). Taiyuan South Station also offers direct coaches to the scenic area (2.5-3 hours). By Bus: From Beijing, overnight sleeper buses reach Taihuai Town directly (about 8-9 hours). Getting Around: Within the scenic area, a shuttle bus system connects Taihuai Town to the five terraces and major temples (CNY 50-60 per day). Hiking between terraces (the 'Grand Circuit') takes 3-5 days and requires a licensed guide or proper gear. Entry Fee: CNY 135 (peak) / CNY 120 (off-peak), plus shuttle fees.",
    faqs: [
      { q: "Is Mount Wutai worth visiting?", a: "Yes — for travelers interested in living Buddhism, it is unmatched. Wutai is the only one of the four sacred Buddhist mountains with all four of China's major Buddhist traditions (Han, Tibetan, Mongol, and Lotus Sutra) coexisting on one mountain. The contrast between ancient Han temples and Tibetan monasteries with prayer flags, monks chanting at dawn, and the vast high-altitude plateau above 2,500m makes it a place unlike anywhere else in China." },
      { q: "What is the best time to visit Mount Wutai?", a: "June and September offer the best combination: clear visibility over the five terraces, mild temperatures (10-25 C), and smaller crowds than July-August. For the famous sea-of-clouds views, arrive on a clear morning after rain. Winters are spectacular but brutal — temperatures drop below -20 C on the summits and most terrace routes close." },
      { q: "How do I get to Mount Wutai?", a: "The most common route is by high-speed train to Xinzhou West Station (2.5h from Beijing West, 1.5h from Taiyuan), then a 2-2.5 hour bus or taxi to Taihuai Town. Alternatively fly to Taiyuan Wusu Airport and take a direct coach (3.5-4 hours). A shuttle bus system inside the scenic area connects the five terraces and major temples." },
      { q: "How difficult is hiking Mount Wutai?", a: "The Grand Circuit — walking all five terraces over 3-5 days — covers roughly 50-70km at altitudes between 2,300m and 3,058m. It is a demanding multi-day hike with limited facilities between terraces; hire a guide or join a group in Taihuai Town. Most visitors instead take the shuttle to the terraces and walk short sections, which is easy with good shoes." },
      { q: "What should I bring for Mount Wutai?", a: "Layered warm clothing is essential even in summer — temperatures at the North Terrace (3,058m) can be 15 C colder than Taihuai Town. Sunscreen is critical at altitude. If attempting the Grand Circuit, bring a headlamp, trekking poles, and water purification tablets. Cash is needed for temple donations and small food stalls." }
    ]
  },
  meili_snow_mountain: {
    whenToGo:
      "October to January is the golden window. From mid-October the monsoon finally retreats, giving the highest probability of seeing the full 13-peak ridge of Meili Snow Mountain, including the golden sunrise on Kawagarbo (6,740m) — visible on roughly 60-80 days per year, most reliably November-December. May-June brings rhododendron blooms in the valleys and moderate weather, but the summits stay cloud-wrapped most days. July-September is the monsoon: expect rain, mud on the Yubeng trails, and the peak hidden 80%+ of the time, though this is when waterfalls and forests are most lush. February-April can be clear but bitterly cold at altitude, with snow on the trails. Always budget 2-3 days at Feilai Temple to maximize your sunrise odds.",
    howToGetThere:
      "By Air: Fly to Diqing Shangri-La Airport (DIG) — direct flights from Kunming (1h), Chengdu, and Chongqing. From Shangri-La city, buses to Deqin County (Feilai Temple stop) run daily and take 4-5 hours (CNY 60-80). By Bus: From Kunming, night buses reach Deqin in 12-14 hours. From Lijiang, buses via Shangri-La take a full day. Getting to Feilai Temple: The viewing platform at Feilai Temple is 10 minutes walk from the Deqin bus stop; most travelers stay in the hotels strung along the highway here for sunrise views. Yubeng Village: From Xidang (2h drive from Feilai), hike 4-6 hours or take a donkey up to Upper Yubeng. The trek through Yubeng valley to the glacier viewpoints is the classic multi-day hike. Entry Fee: CNY 150 (seasonal); the Yubeng valley area charges a separate environmental fee.",
    faqs: [
      { q: "Is Meili Snow Mountain worth visiting?", a: "Yes — it is arguably the most visually stunning mountain in China and the most sacred peak in Tibetan Buddhism. The 13-peak ridge rises 6,740m from valleys at 2,000m, and the golden sunrise on Kawagarbo from Feilai Temple is one of the great spectacles of Chinese travel. The Yubeng valley trek adds a genuine Himalayan wilderness experience that most Chinese tourist peaks cannot match." },
      { q: "What is the best time to visit Meili Snow Mountain?", a: "November to early January offers the clearest skies and best golden-sunrise odds (60-80 days per year total). October and February are also good. From June to September the monsoon keeps the peak hidden most days. Check the webcam at Deqin before committing to the journey." },
      { q: "How do I get to Meili Snow Mountain?", a: "Fly to Diqing Shangri-La Airport, then take a 4-5 hour bus to Deqin County (get off at Feilai Temple for the classic sunrise viewpoint). From Lijiang it is a full day overland. To reach Yubeng village, drive 2 hours to Xidang and hike 4-6 hours (or ride a donkey) up the valley." },
      { q: "How difficult is hiking Meili Snow Mountain?", a: "The Yubeng trek is moderate — 4-6 hours to Upper Yubeng, then day hikes to the glacier viewpoints (6-8 hours round trip). Altitude is the main factor: Yubeng sits at 3,050m and the viewpoints reach 3,600m, so acclimatize in Shangri-La (3,300m) first. Summiting Kawagarbo itself is forbidden by local belief and mountaineering regulations." },
      { q: "What should I bring for Meili Snow Mountain?", a: "Warm layers — mornings at Feilai Temple (3,400m) are near freezing even in October. Sunscreen and sunglasses are essential at altitude. For the Yubeng trek, bring trekking poles, rain gear (the valley gets afternoon showers year-round), and enough cash — there are no ATMs in the villages. Motion sickness pills for the switchback mountain roads." }
    ]
  },
  guilin: {
    whenToGo:
      "April-May and September-November are the classic windows. Spring (March-May): the Li River runs full, rice terraces at Longji are flooded for planting (April-May — the mirror effect is stunning), and the karst peaks wear fresh green. Temperatures 15-28 C. Summer (June-August): hot (28-35 C) and humid with frequent showers; the river stays scenic but mornings are best for photos, and the famous 'misty karst' look is most likely after rain. Autumn (September-November): the clearest air of the year, golden rice terraces, and comfortable 18-28 C — the best season for photography and cycling the Yulong River valley. Winter (December-February): mild (8-15 C) and quiet, with occasional fog days when the peaks float like ink-wash paintings; boat traffic on the Li River is reduced and some cruises run shorter routes.",
    howToGetThere:
      "By Air: Fly to Guilin Liangjiang International Airport (KWL) — direct flights from Beijing (3h), Shanghai (2.5h), Guangzhou (1.5h), and most major Chinese cities. From the airport, a taxi to downtown Guilin costs about CNY 100-150 (40 min). By High-Speed Train: Guilin North Station is on the Beijing-Guangzhou high-speed line (2.5h from Guangzhou, 5h from Changsha). Guilin West and Guilin stations also serve regional lines. The classic route: From Guilin, take a 4-star Li River cruise to Yangshuo (4-5 hours, CNY 300-400) or the high-speed train (30 min). In Yangshuo, rent an e-bike (CNY 50-100/day) to explore the Yulong River valley and countryside. For Longji Rice Terraces, take a bus from Guilin Bus Station to Ping'an Village or Dazhai (2-3 hours, CNY 50-80). Entry Fee: Li River cruise tickets vary by boat class; Xianggong Hill viewpoint CNY 60; Longji terraces CNY 80.",
    faqs: [
      { q: "Is Guilin worth visiting?", a: "Yes — the karst landscape of the Li River between Guilin and Yangshuo is one of the most photographed landscapes on Earth, and it genuinely delivers. The river cruise is a bucket-list experience, the Yulong River offers quiet bamboo-raft floats away from the big boats, and the Longji rice terraces are among the most dramatic in Asia." },
      { q: "What is the best time to visit Guilin?", a: "September-November offers the clearest air and most reliable weather for river and terrace views. April-May is equally beautiful — the terraces are flooded for planting, creating mirror reflections of the sky, and temperatures are mild. Avoid the hottest weeks of July-August unless you like 35 C humidity." },
      { q: "How do I get to Guilin?", a: "Fly to Guilin Liangjiang Airport from any major Chinese city, or take the high-speed train (2.5h from Guangzhou, 5.5h from Hong Kong West Kowloon). From Guilin, the Li River cruise takes you all the way to Yangshuo, or take the 30-minute high-speed train to Yangshuo station. Longji terraces are 2-3 hours by bus from Guilin." },
      { q: "How difficult is the hiking in Guilin?", a: "The classic karst viewpoints — Xianggong Hill, the Moon Hill climb, and the Longji terrace paths — are easy to moderate 30-90 minute climbs with stone steps. The 3-4 day Li River trek from Guilin to Yangshuo follows flat riverside paths and is suitable for average fitness. Rent a bike or e-bike for the flat Yulong River valley." },
      { q: "What should I bring for Guilin?", a: "A rain jacket or umbrella — showers can appear anytime, especially in summer. Strong insect repellent for riverside evenings. Cash for rural vendors and bamboo raft tips. If visiting Longji, pack light (you carry your own bag up the terraces) and wear shoes with good grip for the wet stone steps." }
    ]
  },
  wudang: {
    whenToGo:
      "April-May and September-October are ideal: 12-25 C, dry trails, and the temples at their photogenic best with spring azaleas or autumn foliage. Summer (June-August) is hot and humid at the base (up to 35 C) but cooler above 1,200m; afternoon thunderstorms are common, and the Golden Summit is often cloud-wrapped by midday — go early. Winter (November-March) is cold (0-10 C) and occasionally snowy; the summit views are the clearest of the year after cold fronts, and the temple halls are nearly empty, but the 9-curve mountain road and cable cars may close during snow. The temple festival of the 3rd lunar month (April) brings pilgrim crowds. Sunrise from the Golden Summit (1,612m) is the single best moment — arrive via the first cable car at 7:30 AM.",
    howToGetThere:
      "By Air: The nearest airports are Wuhan Tianhe (2.5-3h drive) and Xiangyang Liuji (1.5-2h drive); both have connections to major Chinese cities. From Wuhan, take the high-speed train to Wudangshan Station (about 2 hours), then a 20-minute bus (CNY 5) or taxi to the scenic area gate at Shiyan. By High-Speed Train: Wudangshan Station on the Wuhan-Xi'an line is the main gateway. From the station, bus 202 or taxis reach the mountain gate. Alternatively, Shiyan Station (30 min away) is served by more trains. Inside the park: a shuttle bus network (CNY 100 round trip) climbs the winding mountain road to the cable car station at 1,100m; the cable car (CNY 170 round trip) reaches near the Golden Summit. The classic 3-hour stone-step trail from Nanyan to the summit is worth the effort for fit hikers. Entry Fee: CNY 140 (main ticket), plus shuttle and cable car fees.",
    faqs: [
      { q: "Is Wudang Mountain worth visiting?", a: "Yes — it is the most important Daoist mountain in China and a UNESCO World Heritage Site (1994). The 72-peak complex includes the magnificent Purple Cloud Palace, the Nanyan cliff temples, and the Golden Summit temple with its bronze hall cast in 1416. For fans of martial arts, this is the birthplace of taiji (tai chi) and the setting of countless kung fu films." },
      { q: "What is the best time to visit Wudang?", a: "April-May and September-October offer the best weather and views. For the clearest Golden Summit panorama, go on a morning after rain in autumn. Winters can be spectacular but the mountain road and cable car occasionally close in snow; check conditions before traveling." },
      { q: "How do I get to Wudang Mountain?", a: "Take the high-speed train to Wudangshan Station (2h from Wuhan, 4.5h from Xi'an), then a 20-minute bus or taxi to the scenic gate. From Wuhan airport, allow 2.5-3 hours by car or train. Inside the park, shuttle buses climb to the cable car station; the cable car takes you near the Golden Summit in 10 minutes." },
      { q: "How difficult is hiking Wudang?", a: "The cable car handles the summit section, making the core visit easy. For hikers, the classic trail from Nanyan Palace to the Golden Summit is 3 hours of steep stone steps with 500m elevation gain — moderate but rewarding. A full temple circuit on foot covers 10-15km per day with constant stairs." },
      { q: "What should I bring for Wudang?", a: "Comfortable walking shoes with grip — there are thousands of stone steps. A light rain jacket for afternoon showers in summer. Warm layers for the summit at any season (it is 10 C colder than the base). Cash for temple incense (usually CNY 3-10) and cable car tickets if booking on-site." }
    ]
  },
  sanqingshan: {
    whenToGo:
      "April-June: azalea season turns the granite peaks pink at mid-elevations, and the sea of clouds is common in May-June after rain; temperatures 10-25 C. July-August: warm and wet, with frequent mist that obscures the famous pillars — mornings before 10 AM are the clearest window. September-November is the golden season: the driest months, the highest visibility, the famous 'Sanqing mist' at sunrise, and autumn colors in the valleys; 8-20 C. Winter (December-February): below freezing at the summit (often -5 to -10 C), but the rime ice on the granite spires and the near-empty boardwalks create a starkly beautiful landscape; the Western Cable Car may run reduced hours. The sunrise from Yujing Peak (1,819.9m) is the classic photographic moment — stay overnight at a summit hotel.",
    howToGetThere:
      "By Air: Fly to Shangrao Sanqingshan Airport (SQD, opened 2019) or to Nanchang Changbei International Airport (3h drive). By High-Speed Train: Shangrao Station on the Shanghai-Kunming line is the main gateway (2h from Hangzhou, 2.5h from Shanghai). From Shangrao Station, direct buses to the scenic area take 1.5-2 hours (CNY 27). Getting up the mountain: two cable cars — the Southern Cable Car (from Wai Shuangxi, 40 min line in peak season) and the Western Cable Car (from Jinsha, faster access to the main loop). Both cost CNY 125 round trip on top of the CNY 120 entry. The 3.6km suspended boardwalk loop around the summit area is mostly flat and takes 3-4 hours at a relaxed pace. Entry Fee: CNY 120 (peak), CNY 80 (low season).",
    faqs: [
      { q: "Is Mount Sanqing worth visiting?", a: "Yes — it is frequently called 'the Huangshan without the crowds' and it deserves the comparison. The 3.6km cliff-hugging boardwalk weaves through an extraordinary concentration of granite pillars and statuesque peaks, including the Giant Python Emerging from the Cave and the Goddess of the East. As a UNESCO World Heritage Site (2008), it rivals Zhangjiajie's rock formations with far fewer tourists." },
      { q: "What is the best time to visit Sanqing?", a: "September-November for the clearest views and best sea-of-clouds odds. May-June offers azalea blossoms and misty conditions. Avoid weekends and Chinese holidays — the boardwalk is narrow and queues for the cable car can exceed 2 hours. Mornings before 10 AM are always clearer." },
      { q: "How do I get to Mount Sanqing?", a: "Take the high-speed train to Shangrao Station (2.5h from Shanghai, 2h from Hangzhou), then a 1.5-2 hour bus to the scenic area. Use the Western Cable Car (Jinsha) if you want the fastest access to the main summit loop; the Southern Cable Car serves the traditional pilgrimage route." },
      { q: "How difficult is hiking Mount Sanqing?", a: "Surprisingly easy for such dramatic scenery. The main summit loop is a flat, cantilevered boardwalk suspended along cliff faces — no serious climbing required. For more challenge, side trails climb Yujing Peak (1,819.9m) and the West Coast scenic area. A full circuit takes 4-6 hours with cable cars." },
      { q: "What should I bring for Sanqing?", a: "A light rain jacket even in clear weather — the mountain generates its own microclimate. Warm layers for sunrise and the summit at any season. Comfortable flat-soled shoes (the boardwalk is smooth). Snacks and water, as summit food is limited and expensive. A camera with a telephoto lens for the granite pillars." }
    ]
  },
  tianmen: {
    whenToGo:
      "April-May and September-November offer the clearest views of Tianmen Cave and the most comfortable temperatures (12-25 C). The glass skywalk and the cave are both best in the morning before the cloud base rises; arrive at the cable car station by 7:30 AM. Summer (June-August) is hot and humid at the base, and the summit is often fogged in by midday — if you go, be at the cave by 9 AM. The 999 steps to the cave are brutal in summer heat. Winter (December-February) brings occasional snow and rime ice that makes the cave opening even more dramatic; the mountain road may close during ice storms, but the cable car usually runs. Spring (March) has frequent mist — atmospheric but view-limiting. Avoid Golden Week at all costs: queues for the cable car can hit 3+ hours.",
    howToGetThere:
      "By Air: Fly to Zhangjiajie Hehua International Airport (DYG) — direct flights from Beijing, Shanghai, Guangzhou, Chengdu, and Xi'an. Tianmen Mountain's cable car station is only 10 minutes from the airport and downtown Zhangjiajie. By High-Speed Train: Zhangjiajie West Station (new, 2023) is on the Zhangjiajie-Changsha line (3h from Changsha). From downtown, the Tianmen cable car station is a 5-minute taxi ride. The route: take the 7.45km cable car (the longest passenger cable car in the world) up to the summit — 28 minutes with a mid-station at the famous 99-bend mountain road. Walk the cliffside glass skywalk, take the elevator to the cave platform, then descend the 999 steps or take the escalator and shuttle back via the 99 bends. Entry Fee: CNY 261 (cable car + entry combined, the standard package).",
    faqs: [
      { q: "Is Tianmen Mountain worth visiting?", a: "Yes — for the cable car ride alone, which is one of the world's great urban-to-summit cable experiences: 7.45km and 1,300m of vertical gain, including the famous 99-bend road visible below. Add the natural arch of Tianmen Cave (131.5m high), the glass skywalk along the cliff, and the views over Zhangjiajie's karst landscape, and you have a full, unforgettable day." },
      { q: "What is the best time to visit Tianmen?", a: "Autumn (September-November) gives the clearest air and best cave views. Spring and early summer bring the 'Heaven's Gate' cloud phenomenon — clouds streaming through the arch — after rain. Go early (before 8 AM) in any season to beat the fog and the tour groups." },
      { q: "How do I get to Tianmen Mountain?", a: "Fly or take the high-speed train to Zhangjiajie, then a 5-10 minute taxi to the cable car station in the city center. The 28-minute cable car ride IS the main attraction — it climbs 1,300m past the 99-bend road to the summit. Tickets combine entry, cable car, and the summit elevator." },
      { q: "How difficult is the visit?", a: "Easy — the infrastructure does the work. The summit loop is a flat boardwalk, the glass skywalk is a 60m section, and elevators connect the summit to the cave. The optional 999 steps down from the cave are steep but manageable at a slow pace; the escalators beside them are free. Suitable for all ages." },
      { q: "What should I bring for Tianmen?", a: "A jacket even in summer — the summit is 10 C colder than the city. Shoes with good grip for the 999 steps (they are wet with mist much of the day). Cash or mobile payment for snacks at the summit plaza. Arrive before 8 AM in peak season to avoid 2-3 hour cable car queues." }
    ]
  },
  siguniang: {
    whenToGo:
      "June-October is the only full-access season. July-August brings alpine wildflowers at their peak in all three valleys, daytime temperatures 10-25 C, and afternoon thundershowers common after 2 PM — start hikes by 7 AM. September-October is the golden window: the clearest skies of the year, larch forests turning gold at 3,500-4,000m, and the four peaks — especially Yaomei Feng (6,250m) — fully visible; this is prime photography season. Late October-early November adds autumn color before the valleys close. November-May: winter access is possible to Shuangqiao Valley (paved boardwalk) but Changping and Haizi valleys close for snow, and the pass roads from Chengdu can ice over. Spring (April-May) is the dry, windy season with less reliable visibility. Always carry a down jacket — even in August the mornings at 3,800m hover near freezing.",
    howToGetThere:
      "By Air: Fly to Chengdu Shuangliu International Airport (CTU), then either take the 4-5 hour drive over the Balangshan Pass (the new tunnel, open since 2017, shortens the route significantly) or fly on to Jiuzhai Huanglong (JZH) — no, the closest airport with direct road access is Chengdu. By Road: From Chengdu, the classic route is via the Chengdu-Wenchuan-Xiaojin highway: public buses depart from Chengdu Chadianzi Bus Station to Rilong Town (4-5 hours, CNY 100-120). Shared minivans and private hire are faster and more flexible. From Chengdu Shuangliu airport, budget 5 hours by car. Inside the park: three valleys — Shuangqiao (paved road + shuttle buses, easiest), Changping (horse trekking or hiking, 10-14km to the glacier viewpoint), and Haizi (full-day hiking to alpine lakes at 4,000m+). Entry Fee: CNY 150 (2-day ticket CNY 200); shuttle buses in Shuangqiao cost extra (CNY 70).",
    faqs: [
      { q: "Is Mount Siguniang worth visiting?", a: "Yes — it is one of China's most dramatic alpine destinations, often called 'the Alps of the East'. The four snow-capped peaks of Siguniang rise to 6,250m directly above Rilong town, and the three valleys offer everything from easy boardwalk strolls to multi-day treks at 4,000m. It is far less crowded than Emei or Huangshan and rewards both photographers and serious trekkers." },
      { q: "What is the best time to visit Siguniang?", a: "September-October offers the clearest views of the four peaks and golden larch forests. July-August is the wildflower season with warm days and frequent afternoon storms. The valleys close for winter snow from around November to April (Shuangqiao may stay open on clear days). Check road conditions before traveling in shoulder seasons." },
      { q: "How do I get to Mount Siguniang?", a: "From Chengdu, take a bus from Chadianzi Bus Station to Rilong Town (4-5 hours, CNY 100-120) or hire a car (5 hours). The Balangshan Tunnel (2017) avoids the old pass road, making the journey year-round and much safer. Rilong town sits at the park entrance with hotels and restaurants." },
      { q: "How difficult is hiking Siguniang?", a: "Three levels: Shuangqiao Valley is easy (shuttle buses + paved paths, suitable for all ages). Changping Valley is moderate — 10-14km each way on gentle valley trails, often done with horses (CNY 300-500). Haizi Valley is strenuous: a full day climbing from 3,200m to 4,300m with real altitude strain. All hikes require altitude awareness above 3,500m." },
      { q: "What should I bring for Siguniang?", a: "A down jacket is non-negotiable — it freezes at night and mornings even in July. Sunscreen and sunglasses (UV is intense at 3,500-4,000m). For Haizi Valley, bring a daypack with water, high-energy food, and rain gear; a walking pole helps a lot. Cash for horse hire and valley entrance fees." }
    ]
  },
  tianshan: {
    whenToGo:
      "June-September is the only full-access season. June-July brings the famous alpine wildflower bloom on the grasslands below the peaks, with temperatures 15-25 C at Tianchi (Heavenly Lake, 1,900m) and cooler above. August offers the warmest lake swimming and the best road conditions for the higher passes. September brings autumn gold on the larches around the lake and the clearest views of Bogda Peak (5,445m), with daytime temperatures 10-20 C — the best month for photography. October-early November: the lake area stays accessible until snow closes the upper roads, and golden aspens along the rivers are stunning. Winter (November-March) closes most of the scenic area but opens a ski resort at the lower slopes. Late spring (May) is transitional — snow patches remain, roads may close briefly. Note: Xinjiang is 2 hours behind Beijing time; plan for late sunsets and early breakfasts.",
    howToGetThere:
      "By Air: Fly to Urumqi Diwopu International Airport (URC) — direct flights from Beijing (4h), Shanghai (5.5h), Guangzhou, Chengdu, and Xi'an, plus international connections. From the airport, Tianchi (Heavenly Lake) is 1.5-2 hours by road (70km). By Road: From Urumqi, the direct highway to Tianchi is well-maintained; public buses leave from the Northern Suburb Bus Station (2h, CNY 40-50), or hire a car for flexibility (CNY 300-400 round trip). Inside the scenic area: shuttle buses climb from the gate to the lakeshore (30 min), and a further cable car or footpath climbs to the upper viewpoints of Bogda Peak. Distances in Xinjiang are vast — a full loop of the Tianshan range (Urumqi to Korla to Kashgar) takes 10+ days overland. Entry Fee: Tianchi CNY 155 (includes shuttle); cable car extra (CNY 220 round trip).",
    faqs: [
      { q: "Is Tianshan worth visiting?", a: "Yes — Tianchi (Heavenly Lake) is the most accessible and beautiful of the Tianshan's alpine lakes, set against the 5,445m snow pyramid of Bogda Peak. The contrast of emerald lake, spruce forests, and permanent snowfields is unlike anything in eastern China, and it is an easy day trip from Urumqi. For deeper exploration, the Tianshan range stretches 2,500km across Xinjiang with vast grassland passes and glacial valleys." },
      { q: "What is the best time to visit Tianshan?", a: "June-September is the season. July-August for wildflowers and the warmest lake conditions; September for golden larches and the clearest Bogda views. Winter closes the upper scenic area. Check the Tianchi webcam for cloud cover — the lake is most beautiful on clear mornings." },
      { q: "How do I get to Tianshan?", a: "Fly to Urumqi, then take a 1.5-2 hour bus or car to the Tianchi scenic area (70km). From the gate, shuttle buses reach the lakeshore in 30 minutes. Note Xinjiang's 2-hour time offset from Beijing — plan your day around local time, not your phone's default." },
      { q: "How difficult is hiking Tianshan?", a: "The Tianchi area is easy — shuttle buses and a gentle lakeside boardwalk suit all ages. The climb to the upper viewpoints (2,500m) is a moderate 1-2 hour hike with stone steps. For serious trekking, the multi-day Karajun grassland routes in the western Tianshan require guides and camping permits." },
      { q: "What should I bring for Tianshan?", a: "A warm layer for the lakeside (it is 10-15 C cooler than Urumqi). Sunscreen — the high-altitude sun at 1,900-2,700m is intense. Snacks and water (facilities at the lake are limited and pricey). Cash or Alipay/WeChat Pay for tickets and shuttle buses." }
    ]
  },
  songshan: {
    whenToGo:
      "April-May and September-October offer the best balance: 15-28 C, clear air, and the Shaolin Temple grounds at their greenest. Spring is the pilgrim season for the Zhongyue Temple fair (3rd lunar month), adding folk performances to the mountain. Summer (June-August) is hot (30-38 C) — the Songshan ridges are exposed and shade is scarce, so climb early and carry water; this is also when the famous Shaolin martial arts performances run most frequently. Autumn (September-November) brings crisp air and the best views from Jijun Peak (1,512m) over the surrounding plains. Winter (December-February) is cold (0-10 C) but quiet, with occasional snow dusting the temple roofs; Shaolin and the cable car stay open year-round. The best photograph of the day is the morning light on the pagoda forest at Shaolin.",
    howToGetThere:
      "By Air: Fly to Zhengzhou Xinzheng International Airport (CGO) — the main gateway for Henan, with flights from all major Chinese cities. From the airport, take the airport shuttle or taxi to Zhengzhou East Station (30 min), then the high-speed train to Dengfeng (about 40 minutes via the Zhengzhou-Dengfeng intercity line, which stops at Dengfeng station). By High-Speed Train: Zhengzhou East Station is on the Beijing-Guangzhou line (2.5h from Beijing, 1.5h from Xi'an). From Zhengzhou East, direct buses to Dengfeng take 1.5 hours (CNY 40). From Dengfeng town, bus 1 or taxis reach the Songshan scenic area gates (10-15 min). Songshan has two main areas: Shaolin Temple (west, with the pagoda forest and martial arts school) and the Zhongyue Temple/Taishi Ridge (east). The shuttle between them takes 30 minutes. Entry Fee: Shaolin CNY 100 (2024); Taishi Ridge CNY 80; combination tickets available.",
    faqs: [
      { q: "Is Mount Song worth visiting?", a: "Yes — Songshan is the Central Great Mountain and the home of Shaolin Temple, the most famous Buddhist monastery on Earth and the birthplace of Shaolin kung fu. Beyond the temple, the Zhongyue Temple is one of China's oldest and grandest Daoist complexes, and the 'Songyang Academy' is one of the four great classical academies. The 1,512m ridges deliver genuine views, and the site as a whole is a UNESCO World Heritage property (2010)." },
      { q: "What is the best time to visit Mount Song?", a: "April-May and September-October for the most comfortable climbing weather and the best light on the pagoda forest. Spring also brings the Zhongyue Temple fair with folk performances. Summer mornings (before 9 AM) are the only sensible climbing window in the 38 C heat." },
      { q: "How do I get to Mount Song?", a: "Fly or take the high-speed train to Zhengzhou, then take the 40-minute intercity train to Dengfeng, or a 1.5-hour direct bus from Zhengzhou East Station. From Dengfeng town, taxis and bus 1 reach the Shaolin Temple and Taishi Ridge gates in 10-15 minutes." },
      { q: "How difficult is hiking Mount Song?", a: "The Shaolin Temple complex itself is flat and easy. The Taishi Ridge climb to Jijun Peak (1,512m) is a 2-3 hour stone-step ascent — moderate, with a cable car available for part of the route. The ridge walk between the two scenic areas is 4-5 hours and exposed; carry water. Day visitors usually stick to Shaolin plus the cable car." },
      { q: "What should I bring for Mount Song?", a: "Water — the ridges are exposed with limited vendors. Sunscreen and a hat for the open ridges. Comfortable shoes for stone steps. If visiting Shaolin, arrive by 9 AM to see the martial arts demonstrations (10:30 AM and 3 PM typically) and avoid the midday tour-bus crowds." }
    ]
  },
  hengshan_hunan: {
    whenToGo:
      "Late spring (May-June) brings blooming rhododendrons at mid-elevations and mild 15-28 C weather. Autumn (September-November) is the classic season: crisp air, the famous sea of clouds above Zhurong Peak (1,300.2m) after cold fronts, and fewer pilgrims. Summer (July-August) is hot and humid at the base (up to 37 C), but the upper mountain stays 8-10 C cooler, and the night climb to see the sunrise is a beloved local tradition year-round. Winter (December-February) occasionally dusts the temples and ridges with snow — the Nanyue Temple and Zhurong Peak look spectacular under a light cover, and the mountain stays open. Peak pilgrim times: the birthday of the Fire God (6th lunar month) and Lunar New Year bring tens of thousands of incense-burning pilgrims to Nanyue Temple — atmospheric but extremely crowded.",
    howToGetThere:
      "By Air: Fly to Changsha Huanghua International Airport (CSX), then take the high-speed train from Changsha South to Hengshan West Station (about 30 minutes), or drive 2 hours directly. By High-Speed Train: Hengshan West Station on the Wuhan-Guangzhou line is the gateway (2h from Guangzhou, 2.5h from Wuhan). From the station, a 20-minute bus (CNY 10) or taxi (CNY 40-50) reaches the Nanyue town scenic gate. Inside the park: shuttle buses climb the mountain road to the cable car mid-station (about 30 min), and the cable car (CNY 90 round trip) finishes the ascent to near Zhurong Peak. Fit hikers follow the classic stone-step trail from Nanyue Temple — roughly 4-6 hours to the summit with 1,200m of gain. The night climb for sunrise is popular and the trail is well-lit with vendors at intervals. Entry Fee: CNY 110 (peak) / CNY 80 (off-peak).",
    faqs: [
      { q: "Is Mount Heng (Hunan) worth visiting?", a: "Yes — as the Southern Great Mountain, it anchors the south of the Wuyue system and is a major center of Chinese fire worship centered on Zhurong, the mythical god of fire and the hearth. The Nanyue Temple is one of the largest and best-preserved temple complexes in China (its architecture mixes north and south styles), and the mountain holds over 200 temples, nunneries, and shrines along its slopes." },
      { q: "What is the best time to visit Mount Heng?", a: "September-November for clear air and sea-of-clouds views from Zhurong Peak; May-June for rhododendron blooms and mild weather. The famous sunrise-watching night climb is best in autumn. Avoid the 6th lunar month fire-god festival and Lunar New Year unless you enjoy huge pilgrim crowds." },
      { q: "How do I get to Mount Heng?", a: "Take the high-speed train to Hengshan West Station (30 min from Changsha South, 2h from Guangzhou), then a 20-minute bus or taxi to the Nanyue scenic gate. From Changsha airport, allow 2 hours door-to-door. Inside, shuttle buses and the cable car do most of the climbing." },
      { q: "How difficult is the climb?", a: "Easy if you use the shuttle bus plus cable car — a pleasant half-day temple visit. The full stone-step trail from Nanyue Temple to Zhurong Peak is a demanding 4-6 hour ascent (1,200m gain) that is a rite of passage for fit hikers. The night climb for sunrise is strenuous but the trail is well-lit and busy even at 3 AM." },
      { q: "What should I bring for Mount Heng?", a: "Warm layers — the summit is 8-10 C colder than the base, and night climbers need a jacket even in summer. Headlamp for the night climb. Comfortable shoes with grip. Cash for incense (the fire-god tradition means most visitors buy incense bundles) and trail snacks." }
    ]
  },
  hengshan_shanxi: {
    whenToGo:
      "May-June and September-October offer the best balance: 10-25 C, dry trails, and clear views from Tianfeng Ridge (2,016.1m). Summer (July-August) is warm (up to 30 C) and this is the busiest season, with the Hanging Temple queues peaking; mornings before 9 AM are essential. The view from the ridge after summer rain — clouds rolling through the canyons below — is the mountain's signature sight. Autumn (September-November) is the photographers' window: golden foliage on the slopes, crisp air, and the Hanging Temple glowing in low light. Winter (December-February) is cold (-5 to 10 C) and often windy; the Hanging Temple stays open but the upper mountain paths can ice over — bring crampons if hiking. The temple is best photographed at opening time (8 AM) when the light hits its southern facade.",
    howToGetThere:
      "By Air: Fly to Datong Yungang Airport (DAT) — direct flights from Beijing, Shanghai, Guangzhou, and Xi'an. From the airport, the Hanging Temple (Xuankong Si) is about 1.5 hours by road (70km) to Hunyuan County. By High-Speed Train: Datong South Station on the Beijing-Zhangjiakou-Datong line (2h from Beijing) or the Datong-Taiyuan line. From Datong South, buses and taxis reach Hunyuan County (1-1.5 hours, CNY 30-60). The Hanging Temple sits on the cliff road between Hunyuan and Mount Heng's main gate — buses to the mountain pass the temple. To reach the ridge: from the main gate, shuttle buses climb to the cable car station; the cable car (CNY 70 round trip) or a 2-hour stone-step climb reaches the summit area. Entry Fee: Hanging Temple CNY 115; Mount Heng CNY 45; cable car extra.",
    faqs: [
      { q: "Is Mount Heng (Shanxi) worth visiting?", a: "Yes — for the Hanging Temple (Xuankong Si) alone, one of the most extraordinary buildings in China: a 1,500-year-old complex of 40 halls and pavilions suspended on wooden beams from a sheer cliff face, built where a river canyon funnels the wind. Above it, the Northern Great Mountain offers quiet ridge walking (far fewer tourists than its southern namesake) and is one of the five peaks least visited by foreigners." },
      { q: "What is the best time to visit Mount Heng?", a: "May-June and September-October for the best ridge weather. For the Hanging Temple, arrive at 8 AM opening — the light is perfect and the crowds are manageable. Winters are cold and icy but the temple looks dramatic against snow. Summer weekends are extremely busy." },
      { q: "How do I get to Mount Heng?", a: "Fly or take the high-speed train to Datong (2h from Beijing by train), then 1-1.5 hours by road to Hunyuan County. The Hanging Temple is on the road between Hunyuan and the mountain gate, so most visitors see it first, then continue to the ridge. Shuttle buses and a cable car handle the upper mountain." },
      { q: "How difficult is hiking Mount Heng?", a: "The Hanging Temple visit is easy — short stairs and boardwalks. The climb from the main gate to Tianfeng Ridge is 4-5 hours of stone steps (about 1,200m of gain) if you skip the cable car, or a 30-minute ride plus 30-60 minutes of walking if you take it. The ridge trails are well-maintained and moderate." },
      { q: "What should I bring for Mount Heng?", a: "A jacket — the exposed ridge is windy at 2,000m even in summer. Comfortable shoes for stone steps. Cash for the Hanging Temple ticket and shuttle buses. If visiting in winter, crampons or microspikes for icy paths, and check whether the upper mountain is open." }
    ]
  },
  jiuhuashan: {
    whenToGo:
      "April-May for mild weather and blooming azaleas among the temples; September-October for crisp air, the famous misty mornings, and autumn color on the slopes. Both windows offer 10-25 C and the clearest views from Shiwang Peak (1,342m). Summer (June-August) is warm and humid (up to 33 C) with afternoon showers; the mountain's many temple halls stay cool, and this is the season of the Ksitigarbha festival (7th lunar month) when pilgrims arrive in large numbers. Winter (December-February) brings occasional snow that turns the temple roofs and the '99 temples' into an ink-painting scene; temperatures range -2 to 8 C, and the cable car and main temples stay open. The best photographs are the morning incense smoke rising through the mist over the Jiuhua street temples.",
    howToGetThere:
      "By Air: Fly to Chizhou Jiuhuashan Airport (JUH) — direct flights from Shanghai, Guangzhou, Shenzhen, Xi'an, and Chengdu. From the airport, a 1-hour bus or taxi reaches the scenic area. By High-Speed Train: Chizhou Station on the Shanghai-Wuhan line (about 2.5h from Shanghai) is the main rail gateway; buses from Chizhou to Jiuhua Mountain take 1-1.5 hours (CNY 30-40). By Road: From Nanjing or Hefei, direct buses reach the mountain gate (3-4 hours). Getting around: The scenic area centers on Jiuhua Street (the 'temple town' at 650m) where most pilgrims stay. From there, a shuttle bus system (CNY 50) connects the major temples, and a cable car (CNY 160 round trip) climbs to the Tiantai summit area at 1,306m. Entry Fee: CNY 190 (peak) / CNY 140 (off-peak) — one of the more expensive Chinese scenic areas.",
    faqs: [
      { q: "Is Mount Jiuhua worth visiting?", a: "Yes — it is the sacred mountain of Ksitigarbha (Dizang), the bodhisattva who vowed to empty the hells, and the burial site of Kim Qiaoque, the Korean monk recognized as his incarnation. With 99 temples scattered across its slopes, it is the most temple-dense of the four sacred Buddhist mountains, and the 'temple town' of Jiuhua Street is a living pilgrimage community unlike anything in China's more commercialized peaks." },
      { q: "What is the best time to visit Mount Jiuhua?", a: "September-October for the clearest views and misty temple-town mornings; April-May for azaleas and mild weather. The Ksitigarbha festival in the 7th lunar month (August-September) is the most atmospheric — and most crowded — time to come. Winter snow scenes are beautiful if you don't mind the cold." },
      { q: "How do I get to Mount Jiuhua?", a: "Fly to Chizhou Jiuhuashan Airport (1h transfer) or take the high-speed train to Chizhou Station (2.5h from Shanghai), then a 1-1.5 hour bus. From Nanjing or Hefei, direct coaches reach the gate. Inside, shuttle buses connect the temples and a cable car climbs to the Tiantai summit." },
      { q: "How difficult is the visit?", a: "The core experience — Jiuhua Street temples plus the cable car to Tiantai — is easy. The classic pilgrim climb of the 1,500+ stone steps to the Tiantai summit (if skipping the cable car) takes 2-3 hours and is moderate. The Huacheng Temple area at street level is flat walking." },
      { q: "What should I bring for Mount Jiuhua?", a: "A light rain jacket — mist and drizzle are common. Cash for incense and temple donations (many pilgrims buy incense bundles at the street stalls). Comfortable shoes; the street itself is steep in places. If visiting in summer, insect repellent for evening walks." }
    ]
  },
  putuoshan: {
    whenToGo:
      "April-June offers the best balance: 15-25 C, blooming camellias and azaleas, and the island's famous sea mist creating atmospheric temple views. September-November is the second peak window with crisp air and the clearest views of the 33m Guanyin statue. July-August is peak season: hot (28-33 C), humid, and crowded, but this is also when the island's beaches (Hundred Step Beach, Thousand Step Beach) are swimmable. Winter (December-February) is mild (5-15 C) and quiet, with fewer ferries; the Guanyin birthday festival (19th day of the 2nd lunar month, around March) brings tens of thousands of pilgrims and is the most significant event of the year. Typhoons (July-September) occasionally close the ferries for 1-3 days — check weather before traveling.",
    howToGetThere:
      "By Air: Fly to Ningbo Lishe International Airport (NGB) or Zhoushan Putuoshan Airport (HSN, smaller, flights from Beijing/Shanghai/Guangzhou/Fuzhou). From Ningbo, take the high-speed train to Ningbo South or the direct ferry from the Ningbo Baifeng Ferry Terminal to Putuo (about 2-2.5 hours by boat). By Ferry: The most common route is from Shenjiamen (Zhoushan Island) — ferries run frequently (20-30 min, CNY 30-40). From Shanghai, the Wusongkou ferry to Putuo takes about 12 hours overnight; a fast ferry from Shanghai South (Xiaoyangshan) takes 4 hours. By High-Speed Train: Ningbo station connects to Shanghai (2h) and Hangzhou (1h); from Ningbo, take a bus to Shenjiamen (1.5h) then the ferry. Entry Fee: CNY 160 (Nov-Mar) / CNY 200 (Apr-Oct). Island shuttle buses (CNY 5-10 per ride) connect the temples and beaches.",
    faqs: [
      { q: "Is Mount Putuo worth visiting?", a: "Yes — Putuoshan is the only island among the four sacred Buddhist mountains, and it is the seat of Guanyin (Avalokitesvara), the bodhisattva of compassion — the most beloved figure in Chinese Buddhism. The combination of a sea-girt island, sandalwood incense, chanting monks, and the 33m golden Guanyin statue at the southern tip is unique in China. The coastal cliff paths and hidden coves also make it a genuinely beautiful place to walk." },
      { q: "What is the best time to visit Mount Putuo?", a: "April-June and September-November for the best weather and views. The Guanyin birthday (2nd lunar month, around March) is the most atmospheric pilgrim time but the island is packed. Avoid July-September typhoon season for ferry reliability — check the port notice board or weather app before traveling." },
      { q: "How do I get to Mount Putuo?", a: "The standard route is high-speed train to Ningbo, bus to Shenjiamen (1.5h), then a 20-30 minute ferry to the island. Direct ferries also run from Shanghai (overnight) and Zhoushan airport (HSN) has flights from major cities. Once on the island, shuttle buses connect everything." },
      { q: "How difficult is visiting Mount Putuo?", a: "Easy — the island is small (12.5 sq km) and the shuttle buses connect the main sites. The most rewarding walk is the coastal path from the Guanyin statue around the southern coves (2-3 hours, gentle). The climb to the Fuding Summit viewpoint is 30-45 minutes of stone steps — moderate." },
      { q: "What should I bring for Mount Putuo?", a: "Light layers — the sea breeze is cool even in summer. Sunscreen and a hat for the coastal paths. Cash for ferry tickets and temple incense. If visiting in July-September, a flexible itinerary in case typhoons delay the ferries." }
    ]
  },
  qingcheng: {
    whenToGo:
      "March-May and September-October are ideal: 12-25 C, the famous 'green city' at its freshest, and manageable crowds. Summer (June-August) is the busy season — the front mountain trails and the cable car queues fill with domestic tourists escaping Chengdu's heat, and afternoon storms are common; mornings are best. Autumn (September-November) delivers the clearest air and the photogenic golden ginkgo trees in the temple courtyards. Winter (December-February) is quiet and mild (0-12 C), with occasional snow dusting the green roofs — the most peaceful time to experience the Daoist temples. The rear mountain (Hou Shan) is less developed and emptier in all seasons, with 5-6 hour hiking circuits. The annual Daoist festival on the 3rd lunar month celebrates Zhang Daoling's founding of the Celestial Masters school.",
    howToGetThere:
      "By Air: Fly to Chengdu Tianfu or Shuangliu International Airport, then take the Chengdu metro line 2 to Xipu, the Chengdu-Guanxian intercity train to Qingchengshan Station (about 30 minutes from Chengdu city center), then a 10-minute bus or taxi to the front gate. By High-Speed Train: The Chengdu-Qingchengshan intercity line runs from Chengdu Xipu Station every 30-40 minutes (CNY 15); Qingchengshan Station is at the mountain's foot. By Road: Buses from Chengdu Chadianzi and Xinnanmen stations reach Dujiangyan city (1h), from where bus 101 continues to Qingcheng. Combine the visit with the nearby Dujiangyan irrigation system (30 min away) — together they form one UNESCO World Heritage property (2000). Entry Fee: Front mountain CNY 80; rear mountain CNY 20; cable car CNY 60 one way.",
    faqs: [
      { q: "Is Mount Qingcheng worth visiting?", a: "Yes — this is the birthplace of Daoism, where Zhang Daoling founded the Celestial Masters (Tianshi) school in 142 AD. The front mountain is a cascade of 36 Daoist temples connected by stone paths under a dense green canopy — the reason for its nickname 'the greenest mountain under heaven' (Qingcheng Tianxia You). The rear mountain offers wilder waterfalls and empty trails. It is also a convenient half-day or full-day trip from Chengdu, and pairs perfectly with the Dujiangyan irrigation project." },
      { q: "What is the best time to visit Mount Qingcheng?", a: "March-May and September-October for the best weather and light. The Tianshi Cave temple is most atmospheric in light rain, when mist threads through the pines. Summer weekends are crowded — go on a weekday or use the rear mountain. Winters are quiet and occasionally snowy." },
      { q: "How do I get to Mount Qingcheng?", a: "Take the intercity train from Chengdu Xipu Station to Qingchengshan Station (30 min), then a 10-minute bus or taxi to the gate. Or take a bus from Chengdu to Dujiangyan (1h) and connect with bus 101. Combine with the Dujiangyan irrigation system, 30 minutes away." },
      { q: "How difficult is hiking Mount Qingcheng?", a: "The front mountain loop is a 3-4 hour circuit with constant stone steps and some steep sections — moderate. A cable car covers the steepest part for those who prefer. The rear mountain circuit takes 5-6 hours with more elevation and fewer facilities — harder but rewarding. Both are well-marked." },
      { q: "What should I bring for Mount Qingcheng?", a: "Comfortable shoes with grip — the paths are damp with moss after rain. A light rain jacket. Snacks and water for the rear mountain (fewer vendors). Cash for temple incense and the cable car. Mosquito repellent in summer." }
    ]
  },
  danxia: {
    whenToGo:
      "The colors are visible year-round, but the light is everything. June-September brings the most vivid hues — rain deepens the saturation of the reds and yellows, so a brief shower followed by sun is the photographer's jackpot. July-August is the busiest and hottest (up to 35 C at midday); go at 7 AM opening or 4-5 PM for the famous sunset glow. Late September-October offers the best overall conditions: clear skies, 10-25 C, and golden light that makes the striping pop. November-April is cold (-10 to 10 C) and dry; mornings can be hazy with dust, but frost-light sunrises are spectacular and the boardwalks are nearly empty. Sunrise and sunset are non-negotiable for the signature rainbow bands — low-angle light amplifies every stratum. Flat white cloud cover drains all color, so check the weather before committing a full day.",
    howToGetThere:
      "By Air: Fly to Zhangye Ganzhou Airport (YZY) — direct flights from Beijing, Xi'an, and Lanzhou — or fly to Lanzhou Zhongchuan and connect by high-speed rail. By High-Speed Train: Zhangye West Station sits on the Lanzhou-Xinjiang line (4h from Lanzhou, 5h from Xining, 6h from Xi'an). From the station, the Linze Danxia scenic area is 40 minutes by taxi (CNY 100-150) or about an hour by bus. Getting There: The scenic area is 40km west of Zhangye city. Public buses from Zhangye Bus Station run to Linze Danxia roughly hourly (CNY 15-20). Taxis cost CNY 100-150 each way; a day-hire with waiting time is CNY 300-400. Entry Fee: CNY 75, which includes the mandatory shuttle buses between the four viewing platforms — platform No. 4 is the classic sunset spot. The Ice Valley Danxia and Pingshan Lake Grand Canyon lie 30-40 minutes further west; combine them for a full day.",
    faqs: [
      { q: "Is Zhangye Danxia worth visiting?", a: "Yes — the Rainbow Mountains are one of the most visually singular landscapes on Earth and the photographs do not exaggerate. Unlike a traditional peak, the experience is about color and light rather than summit views: 510 sq km of striped sandstone hills that shift from crimson to gold to purple as the sun moves. For photographers it is arguably the highest-return destination in western China — a full day costs about CNY 75 and delivers images found nowhere else." },
      { q: "What is the best time to visit Zhangye Danxia?", a: "June-September for the most saturated colors (a passing rain shower followed by sun is the jackpot moment), with sunrise and sunset light essential. Late September-October adds comfortable temperatures and clear skies. November-April is cold and dry but empty. Avoid midday in summer — the harsh overhead light flattens the striping and the platforms are crowded." },
      { q: "How do I get to Zhangye Danxia?", a: "Take the high-speed train to Zhangye West Station (4h from Lanzhou, 6h from Xi'an), then a 40-minute taxi (CNY 100-150) or hourly bus to the scenic gate. Alternatively fly to Zhangye Ganzhou Airport. Entry includes shuttle buses that move you between the four viewing platforms." },
      { q: "How difficult is the visit?", a: "Very easy — this is a viewing experience, not a hike. Shuttle buses connect four platform complexes, each requiring only short boardwalk strolls (30-60 minutes total across the site). Suitable for all ages and fitness levels. The only challenge is the high-altitude sun (the site sits around 1,800m) and wind on the exposed platforms." },
      { q: "What should I bring for Zhangye Danxia?", a: "Sunglasses and a hat (the glare off the rock is intense), a warm layer for sunrise/sunset (temperatures drop fast at dusk), a camera with a telephoto lens (85-200mm works best for the striping detail), and water. A dust mask helps in windy spring weather. Entry is by QR ticket — have your phone charged." }
    ]
  },
  haba_snow_mountain: {
    whenToGo:
      "May-June is the classic spring window: stable weather, rhododendrons in bloom up to the treeline, and the snowpack on the standard route consolidated but not icy. September-October is equally reliable — the monsoon has ended, skies clear, views of Jade Dragon and the Meili range improve dramatically, and base camp temperatures hover near freezing but stay manageable. July-August is monsoon: daily afternoon rain, a heavily crevassed glacier, and visibility often zero above 4,500m — technically possible but statistically unpleasant. November-April is winter: the route snows in, avalanche risk rises, and base camp hits -20 C; only experienced teams with full winter gear should attempt it. Climbing windows are short — add 2-3 buffer days in Lijiang or Shangri-La for weather. Summit day runs a 3-4 AM alpine start to reach the top by mid-morning before clouds build.",
    howToGetThere:
      "By Air: Fly to Lijiang Sanyi International Airport (LJG) — direct flights from Beijing, Shanghai, Chengdu, Kunming, and Guangzhou — or to Diqing Shangri-La Airport (DIG) for the northern approach. By Road: From Lijiang, head north on the G214 past Tiger Leaping Gorge to Haba Village (about 3 hours, 110km). Buses run from Lijiang Bus Station to Qiaotou (2h), then a local van climbs the final hour into the valley; most climbers arrange a car or join a group through a Lijiang guesthouse. From Shangri-La it is 2.5-3 hours via the gorge rim. The Climb: from Haba Village (2,700m), trek 5-6 hours through forest to base camp (4,100m); yaks and horses carry gear (CNY 150-300). Summit day adds 1,200m over 6-8 hours. A registered guide is effectively mandatory — hire through your guesthouse (CNY 500-800 for the expedition). No park entry fee.",
    faqs: [
      { q: "Is Haba Snow Mountain worth visiting?", a: "Yes — if you want a true 5,000m+ summit without technical climbing, Haba is the best-value peak in China. It is higher than any point in the contiguous United States, yet the standard route needs no rock or ice skills. The summit panorama — Jade Dragon, Tiger Leaping Gorge, and on clear days the Meili range — is spectacular, and the trek through rhododendron forest to base camp is beautiful in its own right." },
      { q: "What is the best time to climb Haba?", a: "May-June and September-October are the reliable windows: stable weather and safe glacier conditions. July-August is monsoon season with daily rain and poor visibility. November-April is winter — avalanche risk and -20 C base camp temperatures make it an expert-only season. Budget 3-4 days total from Lijiang." },
      { q: "How do I get to Haba Snow Mountain?", a: "Fly to Lijiang (direct flights from most Chinese cities), then drive 3 hours north past Tiger Leaping Gorge to Haba Village. From the village, trek 5-6 hours to base camp (4,100m) with pack animals available. A guide is effectively required and costs CNY 500-800 for the multi-day expedition." },
      { q: "How difficult is climbing Haba?", a: "Technically easy but physically and altitude-demanding. The summit day involves 1,200m of elevation gain over 6-8 hours with crampons, ice axe, and rope travel on the final snow slope. At 5,396m oxygen is about 50% of sea level. Excellent fitness, comfort with altitude, and proper equipment are essential — no prior mountaineering experience is required." },
      { q: "What should I bring for Haba?", a: "A down sleeping bag rated to -10 C or colder (base camp is cold in all seasons), crampons, ice axe, helmet, headlamp with spare batteries (you start in darkness), warm layers including a down jacket, sunscreen, and high-energy food. Trekking poles help on the long forest section. Rent gear in Lijiang or Shangri-La if you don't own it." }
    ]
  },
  namcha_barwa: {
    whenToGo:
      "October-November is the only reliable window for seeing the peak: the monsoon retreats, the Yarlung Tsangpo valley air clears, and Namcha Barwa's 7,782m east face is visible on roughly 40% of days — the annual average is only 30-40 clear days, most of them in autumn. March-April is the second window: Nyingchi's peach blossoms turn the valley floor pink while the peak still carries full winter snow, but afternoon cloud is more common. May-September is monsoon: the peak hides virtually every day and canyon roads can be blocked by landslides. December-February is dry and clear but very cold (valley nights near -10 C) and some passes close. Stay 2-3 days to spread your odds across multiple sunrises and sunsets. The classic viewpoints are Serkem La pass and the Pai village bend on the G318.",
    howToGetThere:
      "By Air: Fly to Nyingchi Mainling Airport (LZY) — one of the most dramatic approach flights on Earth, threading between the peaks of the eastern Himalaya. Flights from Chengdu (1.5h), Chongqing, and Xi'an operate most days. From Mainling, the viewing area around Pai village and Serkem La is 2-3 hours by car. By Road: From Lhasa, the G318 takes 2 days via Basum Tso (overnight) — the classic road trip; the new Lhasa-Nyingchi expressway cuts it to 6-7 hours. Permits: Nyingchi requires a Tibet Travel Permit arranged through a licensed agency, usually bundled with an organized tour since independent travel is restricted for foreign visitors. Budget: an organized 4-5 day Lhasa-Nyingchi loop including the canyon costs roughly CNY 3,000-5,000 per person. The Yarlung Tsangpo Grand Canyon park (CNY 150) has shuttle viewpoints; the best free views are at Serkem La and along the G318 near the canyon bend.",
    faqs: [
      { q: "Is Namcha Barwa worth visiting?", a: "Yes — for travelers willing to make the journey, it is one of the most awe-inspiring sights in China: a 7,782m peak rising almost 5,000m in just 20 horizontal kilometers above the deepest canyon on Earth. It is also deeply sacred to Tibetan Buddhism. The experience is about witnessing and atmosphere, not activity — and the autumn visibility, though limited, rewards patience spectacularly." },
      { q: "What is the best time to visit Namcha Barwa?", a: "October-November offers the best peak visibility (roughly 40% of days) with crisp autumn air. March-April pairs a snow-laden peak with Nyingchi's peach-blossom valleys. June-September is monsoon season — the peak is almost always hidden. Stay 2-3 nights and check the local webcams before committing to early mornings." },
      { q: "How do I get to Namcha Barwa?", a: "Fly to Nyingchi Mainling Airport (1.5h from Chengdu), then drive 2-3 hours to the Pai village / Serkem La viewpoint area. Foreign visitors need a Tibet Travel Permit arranged through a licensed agency — most travelers join an organized Lhasa-Nyingchi tour. The canyon park charges CNY 150; the highway viewpoints are free." },
      { q: "How difficult is visiting Namcha Barwa?", a: "Physically easy — you do not climb or approach the peak; viewing points sit along the highway at 2,900-3,600m. The real demands are logistical: permits, remote roads, and altitude. Allow 4-5 days for a Lhasa-Nyingchi loop, and take altitude seriously if flying directly to Mainling (2,950m)." },
      { q: "What should I bring for Namcha Barwa?", a: "Warm layers — even in October the morning viewings at 3,000m+ are near freezing. A telephoto lens (200mm+) is essential; the peak is 20-30km from the viewpoints. Motion sickness pills for the switchback canyon roads, sun protection, and patience — the mountain appears and disappears in minutes." }
    ]
  },
  gongga: {
    whenToGo:
      "September-October is the premium window: post-monsoon clarity delivers Gongga's west face in full alpenglow from the Yaha Pass treks, and the 4,000m grasslands turn gold. May-June is the second season: rhododendrons bloom on the lower slopes, snow remains photogenic, and Hailuogou glacier is at its most dynamic. July-August is wet — afternoon cloud usually caps the summit, the glacier cable car often runs in fog, and trails turn to mud; mornings before 10 AM are the only reliable window. November-April is cold (Moxi 0-10 C, snow at altitude) but some of the clearest winter air arrives in December-February; the cable car may close in heavy snow. Sunrise from the Hailuogou Cableway top station (3,600m) — 'the Golden Dome' — is the single best moment: the summit catches light 10-15 minutes before the valley floor.",
    howToGetThere:
      "By Air: Fly to Chengdu Tianfu or Shuangliu International Airport, then continue overland (no closer airport exists). By Road: From Chengdu, the new Ya'an-Kangding expressway cuts the drive to Kangding to 4-5 hours; from Kangding, a 2-3 hour mountain road over the Zheduo Pass leads toward the western viewpoints and the Yaha Pass trek start at Lao Yulin. The eastern approach: Chengdu to Moxi town (base of Hailuogou Glacier Park) is 5-6 hours by bus or car. Public buses run from Chengdu Xinnanmen Station to Kangding (6-7h) and Luding (5-6h); from Luding, buses to Moxi take 1.5 hours. Inside Hailuogou: shuttle buses (CNY 90) climb 40 minutes to the cable car base, and the cable car (CNY 150 round trip) rises to 3,600m in 18 minutes. Acclimatization is essential — spend a night in Kangding (2,560m) or Moxi (1,600m) before going above 3,000m. Entry: Hailuogou CNY 90; the western treks from Lao Yulin are free but require a local guide.",
    faqs: [
      { q: "Is Mount Gongga worth visiting?", a: "Yes — as the King of Sichuan Mountains (7,556m) and the easternmost 7,000m peak on Earth, it offers something no eastern Chinese mountain can: real Himalayan scale without leaving Sichuan. The Hailuogou glacier descends to just 2,850m — one of the lowest in Asia, reachable by cable car — while the western valleys offer remote Tibetan-culture treks beneath a colossal summit." },
      { q: "What is the best time to visit Mount Gongga?", a: "September-October for the clearest summit views and golden grasslands; May-June for rhododendrons and fresh snow. July-August brings monsoon cloud — go early in the day. December-February offers winter clarity but cold and possible cable car closures. Sunrise at the Hailuogou cable car top station is the single best moment." },
      { q: "How do I get to Mount Gongga?", a: "Fly to Chengdu, then take the expressway to Kangding (4-5h) for the western approach or buses to Moxi town (5-6h) for the eastern Hailuogou approach. Inside Hailuogou, shuttle buses and the cable car do the work; the western treks start at Lao Yulin, 2-3 hours from Kangding." },
      { q: "How difficult is visiting Mount Gongga?", a: "The classic visit is easy: shuttle bus plus cable car takes you to 3,600m on the glacier with boardwalk views. The Yaha Pass trek is genuinely demanding — multi-day walking above 4,000m with altitude, weather, and remote logistics; it requires a guide and proper gear. Choose your experience level deliberately and acclimatize first." },
      { q: "What should I bring for Mount Gongga?", a: "A down jacket for the glacier platform (it is 15 C colder than Chengdu at 3,600m), sunscreen and sunglasses (intense UV at altitude), and cash — card acceptance is patchy in Moxi. For the western treks: trekking poles, a warm sleeping bag, and altitude medication. Book Hailuogou tickets online in peak season." }
    ]
  },
  mingsha: {
    whenToGo:
      "May-June and September-October are ideal: 15-30 C days, cool evenings, and the dunes at their most comfortable for walking. Summer (July-August) is intense — surface sand hits 50-60 C by noon, so visits are practical only in the early morning or after 5 PM; the sunset camel caravans are a nightly spectacle but the crowds peak at that hour. Spring (March-April) brings wind and occasional sandstorms — check the forecast and pack a face scarf; the day after each storm has exceptional light. Winter (November-February) is cold (daytime 0-10 C) but magical: the lake freezes shallowly, the dunes are nearly empty, and the low winter sun draws long shadows across the sand. The single best hour is the last hour before sunset, when Crescent Moon Lake reflects gold. The park adjusts opening hours seasonally — for sunset visits, enter 3 hours before closing.",
    howToGetThere:
      "By Air: Fly to Dunhuang Mogao International Airport (DNH) — direct flights from Beijing (3h), Xi'an (2h), Lanzhou (1.5h), and Chengdu, with peak-season connections from Shanghai and Guangzhou. By Train: Dunhuang Station is served by the Dunhuang Railway (overnight from Lanzhou, 8-9 hours; 6 hours from Xining), and the Lanzhou-Xinjiang high-speed line stops at Liuyuan, 130km away (2h by connecting bus). Getting There: Mingsha is only 6km south of Dunhuang city — bus 3 from the city center (CNY 2) or a 15-minute taxi (CNY 20-30). It pairs perfectly with the Mogao Caves (10km east): the classic itinerary is Mogao in the morning, Mingsha at sunset. Entry Fee: CNY 120, valid for 3 days with a second entry; camel rides CNY 100 per loop; sand sliding and ATV tours extra. No guide needed — the dunes are easy to explore independently, and the western rim of the scenic area is quieter than the main valley."
  }
  ,
  yandang: {
    whenToGo:
      "April-May and October-November are the prime windows: 15-25 C, moderate crowds, and the clearest views of the iconic peaks. The signature experience — Lingfeng (Spirit Peak) Night View — works year-round but is best on moonlit nights; the silhouettes of rocks against the sky are a local art form. Summer (June-August) is hot and muggy (28-35 C) with frequent thunderstorms; this is also when the Da Longqiu waterfall runs at full power — after a rain the 197m drop is genuinely thunderous, and the mountains are at their greenest. Autumn (September-November) brings dry air and the best photography light, plus the mid-autumn moon for night viewing. Winter (December-February) is mild (5-15 C) and quiet, with occasional snow dusting the peaks; waterfalls shrink but the night-view silhouettes stay crisp. Avoid Golden Week and summer weekends — the valleys fill with domestic tourists.",
    howToGetThere:
      "By Air: Fly to Wenzhou Longwan International Airport (WNZ) — direct flights from Beijing, Shanghai, Guangzhou, Chengdu, and Xi'an. From the airport, take a bus to Wenzhou South Railway Station, then the high-speed train to Yandangshan Station (about 1 hour). By High-Speed Train: Yandangshan Station sits on the Ningbo-Wenzhou coastal high-speed line — about 2 hours from Hangzhou and 3 hours from Shanghai. The station is only 10 minutes from the scenic area by taxi (CNY 20-30) or shuttle. Getting Around: The scenic area is spread across several valleys — Lingfeng (night views), Lingyan (cliff performances), and Da Longqiu (the big waterfall) are the core trio, each with its own entrance fee. A shuttle bus connects them; the classic itinerary is 2 days — Day 1 Lingfeng + Lingyan, Day 2 Da Longqiu. Entry Fee: individual tickets CNY 40-50 per valley or a combined pass; the cable car at Fangyan saves the steepest climb.",
    faqs: [
      { q: "Is Yandang Mountain worth visiting?", a: "Yes — it is one of China's ten most celebrated mountains and the original home of the Chinese landscape-painting tradition, with sheer volcanic rhyolite cliffs rising above lush valleys. The Lingfeng Night View — rock silhouettes interpreted by moonlight — is a unique cultural experience found nowhere else in China, and Da Longqiu's 197m waterfall is one of the country's most powerful. It is also remarkably accessible from Shanghai and Hangzhou." },
      { q: "What is the best time to visit Yandang?", a: "April-May and October-November for comfortable weather and clear views. Summer after rain is spectacular for the waterfall valleys, and moonlit autumn nights are best for the Lingfeng silhouette views. Winters are mild and quiet. Avoid Golden Week and summer weekends." },
      { q: "How do I get to Yandang Mountain?", a: "Take the high-speed train to Yandangshan Station (2h from Hangzhou, 3h from Shanghai), then a 10-minute taxi or shuttle to the scenic area. By air, fly to Wenzhou Longwan Airport and connect by rail (about 1 hour to Yandangshan Station)." },
      { q: "How difficult is the visit?", a: "Low to moderate. The core valleys are gentle — flat walkways around Da Longqiu, paved paths at Lingfeng, and a short cable car at Lingyan (which also hosts the famous cliff-face kung fu performance). The steeper Fangyan section involves real climbing but is optional. Suitable for families and older travelers." },
      { q: "What should I bring for Yandang?", a: "A camera with a tripod — the night-view silhouettes are the mountain's signature shot. A rain jacket (valley showers come fast), non-slip shoes for the mossy stone paths, and insect repellent for summer evenings. Cash for the valley entrance tickets and local snacks." }
    ]
  },
  laojun: {
    whenToGo:
      "April-May and September-October offer the best sea-of-clouds odds — the classic Laojun photo shows the summit temples floating above a cloud layer, and these months combine clear mornings with reasonable temperatures (10-25 C at the base, cooler at the summit). Summer (June-August) is the monsoon season: the ridge is often cloud-wrapped by mid-morning, but the forest is lush and waterfalls run full — go early. Winter (December-February) transforms the summit into a frozen landscape: rime ice coats the cliffside walkway and the temple roofs, and on clear days visibility is extraordinary; temperatures reach -5 C at the top, so dress accordingly. Autumn (September-November) brings golden sunset light on the Golden Summit temples. Check the webcam before the long drive — the mountain only delivers when the summit is clear.",
    howToGetThere:
      "By Air: Fly to Lijiang Sanyi International Airport (LJG) — direct flights from Beijing, Shanghai, Chengdu, Kunming, and Guangzhou. By Road: From Lijiang, the scenic area is 2.5-3 hours away: head north on the G214 toward Shangri-La, then turn west at the Jianchuan junction toward the Laojunshan Geopark entrance. Public buses from Lijiang to the Laojunshan area are infrequent — most visitors join organized tours or hire a car with a driver (CNY 400-600 round trip), the easiest option for foreign visitors. Getting Up: From the park gate, a cable car climbs toward the summit ridge (about 20 minutes), then a cliffside walkway — including the famous glass section — leads to the Golden Summit temples; the walkway is one-way in peak season. Entry Fee: CNY 100-120 depending on season, plus cable car (CNY 100 round trip). The wider geopark, including alpine lakes and the Yangtze First Bend viewpoint, deserves a full day.",
    faqs: [
      { q: "Is Mount Laojun worth visiting?", a: "Yes — the Golden Summit temple complex balanced on a knife-edge ridge above a sea of clouds is one of the most photographed sacred sites in western China, and it delivers in person. Named for Laozi, the founder of Daoism, it is both a living pilgrimage site and a spectacular viewpoint over the Yangtze First Bend and the Jade Dragon range. It is far less crowded than Jade Dragon Snow Mountain and rewards early risers with extraordinary light." },
      { q: "What is the best time to visit Mount Laojun?", a: "September-October offers the best sea-of-clouds odds and golden sunset light on the temples. April-May is the spring alternative with clear mornings. Winter brings rime-ice scenery and the clearest air but temperatures down to -5 C at the summit. Summer cloud typically obscures the ridge by mid-morning — arrive at the first cable car." },
      { q: "How do I get to Mount Laojun?", a: "Fly to Lijiang, then drive 2.5-3 hours northwest (via the G214 and the Jianchuan junction). Public transport is limited, so most visitors take an organized tour or hire a car with a driver (CNY 400-600 round trip). From the gate, the cable car plus cliffside walkway reaches the summit temples." },
      { q: "How difficult is the visit?", a: "Moderate. The cable car handles the main elevation gain, leaving a 1-2 hour cliffside walkway to the summit — mostly flat with stairs at the ends. The glass walkway is psychologically intense but structurally safe with railings. The full geopark hikes (alpine lakes at 3,800m) are genuinely demanding and need a guide." },
      { q: "What should I bring for Mount Laojun?", a: "A warm windproof layer — the exposed ridge is windy and cold at 3,700m+ even in summer. Non-slip shoes for the walkway (it can be wet), sunscreen at altitude, and cash — card acceptance is limited at the ticket office and village guesthouses. A camera with a wide lens for the summit temples." }
    ]
  },
  shilin: {
    whenToGo:
      "March-April and September-November are ideal: mild 15-25 C, clear air, and the stone formations at their photogenic best. The Sani Torch Festival (late July) brings the area alive with dance, song, and fire — a cultural highlight, but the park is packed. Summer (June-August) is warm (25-30 C) with afternoon showers that make the grey stone glisten; the morning light between 8-10 AM is best for photography, when shadow lines define the karst spires. Winter (December-February) is dry and mild (5-18 C) with thin crowds — a pleasant season, though the wind is sharp on the exposed plateaus. The park is almost entirely paved, so weather affects comfort more than access. A full day covers the Major Stone Forest; a half-day suffices for the main loop.",
    howToGetThere:
      "By Air: Fly to Kunming Changshui International Airport (KMG), then take the metro or a taxi to Kunming South Railway Station (about 40 minutes). By High-Speed Train: The Kunming-Shilin high-speed service runs from Kunming South to Shilin West Station in about 20 minutes — the fastest and most comfortable option. From Shilin West, a 10-minute taxi (CNY 20-30) reaches the park gate. By Bus: Direct buses from Kunming East Bus Station take about 90 minutes (CNY 30-40). Getting Around: The scenic area is large — the electric shuttle bus (included in the ticket) connects the Major Stone Forest, Minor Stone Forest, and Naigu Stone Forest sections. The main loop through the Major Stone Forest takes 2-3 hours on mostly flat paved paths, with stone steps through the densest formations. Entry Fee: CNY 175 (including the shuttle). Combine with lunch in a nearby Sani village — the local cuisine is excellent.",
    faqs: [
      { q: "Is the Stone Forest worth visiting?", a: "Yes — it is a UNESCO World Heritage Site (South China Karst) and the largest and oldest limestone forest on Earth, shaped over 270 million years. Walking among the grey spires, arches, and maze-like passages is like entering a petrified forest, and the Sani people's legends — including the famous Ashima story — give the rocks a living mythology. It is also one of the most accessible half-day trips from Kunming." },
      { q: "What is the best time to visit the Stone Forest?", a: "March-April and September-November for mild weather and clear light. The best photographs come in the early morning (8-10 AM), when the low sun draws shadow lines across the spires. The Sani Torch Festival (late July) is a spectacular cultural addition but the park is crowded. Winters are dry, mild, and quiet." },
      { q: "How do I get to the Stone Forest?", a: "Take the high-speed train from Kunming South to Shilin West Station (about 20 minutes), then a 10-minute taxi to the gate. Alternatively, direct buses from Kunming East Bus Station take 90 minutes. The shuttle bus inside the park connects the Major, Minor, and Naigu sections." },
      { q: "How long does a visit take?", a: "A half-day (3-4 hours) covers the Major Stone Forest main loop with time for photos. A full day adds the Minor Stone Forest and the more remote Naigu section. The terrain is mostly flat and paved — comfortable for all fitness levels, though the steps through the densest formations are steep in places." },
      { q: "What should I bring for the Stone Forest?", a: "Sunscreen, a hat, and water — the exposed plateau sun is strong even in winter. Comfortable non-slip shoes for the stone steps and a wide-angle camera lens for the formations. Cash or mobile payment for the shuttle and village restaurants. Arrive by 9 AM to beat the tour-bus waves." }
    ]
  },
  emeishan: {
    whenToGo:
      "Spring (March to May): Azaleas bloom at higher elevations, temperatures are comfortable (10-20 C), and the forest is lush green. A beautiful season for the full pilgrimage hike.\n\nSummer (June to August): Warm (15-25 C at summit) but often foggy and rainy. The forest is at its greenest. Summer vacation crowds (July-August) are the heaviest. Afternoon thunderstorms are common — start early.\n\nAutumn (September to November): The best season. Clear skies, crisp air, golden foliage, and the highest probability of the Sea of Clouds and Buddha's Light phenomena. October is peak month — book accommodations ahead.\n\nWinter (December to February): Snow-covered and magical. The Golden Summit under snow with the massive golden Samantabhadra statue emerging from mist is one of China's most striking winter scenes. Cable cars operate year-round. Temperatures at the summit drop to -10 C.",
    howToGetThere:
      "By Air: Fly to Chengdu Shuangliu or Tianfu International Airport. From Chengdu, the high-speed train (Chengdu East or South to Emeishan Station) takes about 1 hour, with frequent departures through the day. By High-Speed Train: Emeishan Station is on the Chengdu-Leshan line (1h from Chengdu, 30 min from Leshan and the Giant Buddha). From the station, bus No. 5 or taxis reach the Baoguo Temple entrance at the foot of the mountain in 15 minutes. The classic full-pilgrimage climb starts at Baoguo Temple: 50km of stone steps to the Golden Summit taking 2-3 days, with temples offering simple accommodation along the way. Most visitors instead take the scenic shuttle buses (CNY 90 round trip) up the mountain road to Leidongping, then walk 1.5-2 hours or take the cable car (CNY 55-65) to the Golden Summit (3,079m). Entry Fee: CNY 160 (peak) / CNY 110 (off-peak). Note the summit area sits at 2,500m+ — carry warm layers even in summer."
  },
  jade_dragon: {
    whenToGo:
      "November to April offers the best chance of seeing snow on the mountain. December-February has the most consistent snow cover but cold temperatures (0-10 C at base, -15 C at summit). March-April has warmer temperatures with good snow conditions and blooming wildflowers at lower elevations. May-October is the rainy season — the mountain is often shrouded in clouds, snow cover is minimal, and visibility is poor. Summer offers the lowest chance of seeing the peak clearly. Regardless of season, arrive early — clouds typically build up by late morning, and the mountain is best viewed before 10 AM.",
    howToGetThere:
      "By Air: Fly to Lijiang Sanyi International Airport (LJG) — direct flights from Beijing, Shanghai, Chengdu, Kunming, Guangzhou, and Shenzhen. By High-Speed Train: Lijiang Station is served by the Dali-Lijiang line (about 3.5h from Kunming). From Lijiang Old Town, the mountain entrance is only 15km away — tourist bus No. 7, shared vans (CNY 20-30), or a 40-minute taxi (CNY 100-150). Getting Up: All visitors take cable cars. The Glacier Park cable car (CNY 120) rises from 3,350m to 4,506m — the highest in China and the one with the worst queues; book same-day tickets online from 6-7 AM, as they often sell out. The Spruce Meadow cable car (CNY 60) reaches 3,200m for gentler walks. Entry Fee: CNY 100, with the Glacier Park package totaling about CNY 220. Altitude warning: at 4,506m the top station demands caution — move slowly, carry oxygen (available at the base for CNY 20-40), and skip it if you felt unwell in Lijiang (2,400m)."
  },
  everest: {
    whenToGo:
      "April to May and September to October are the only viable windows. April-May offers the clearest skies and is the main expedition season — you will see expedition tents at base camp and may witness climbers preparing for summit attempts. Daytime temperatures at base camp hover around 0-10 C, dropping to -15 C at night. September-October has slightly more cloud cover but warmer daytime temperatures and fewer tourists.\n\nFrom November to March, the road may be closed by snow, and temperatures plummet to -25 C or lower. The Tibetan Plateau in winter is an extremely harsh environment. June to August is the monsoon season, with cloudy skies that obscure Everest and road closures due to landslides.\n\nRegardless of season, you must spend at least 2-3 days acclimatizing in Lhasa (3,656m) and Shigatse (3,840m) before ascending to base camp. Ascending too quickly from sea level to 5,150m in under 4 days is extremely dangerous.",
    howToGetThere:
      "By Air: Fly to Lhasa Gonggar Airport (LXA) — flights from Beijing, Chengdu, Chongqing, Xi'an, and Shanghai. From Lhasa, the road journey to Everest Base Camp (EBC) takes 3-4 days overland via Shigatse and Tingri, with acclimatization stops (Shigatse at 3,840m, Tingri at 4,300m). By Road: The Friendship Highway (G318) runs from Lhasa through Shigatse to Tingri; from Tingri, the 100km spur road climbs to the base camp area (5,150m). Foreign visitors must join organized tours with licensed guides and obtain a Tibet Travel Permit plus the Alien Travel Permit for EBC (arranged by your agency). Entry Fee: CNY 180 for the base camp area plus a vehicle charge. The final stretch from the gate to the old base camp is a 20-minute shuttle; Everest views are also possible from the Rongbuk Monastery viewpoint. Budget 5-7 days round trip from Lhasa. The base camp sits at 5,150m — altitude sickness is common, so acclimatize in Lhasa for at least 2 nights before heading up."
  },
  hailuogou: {
    whenToGo:
      "October-February: Best glacier views with clear skies. Hot springs at their best in cold weather. Summer brings rain obscuring the peak. Spring offers rhododendron blooms.",
    howToGetThere:
      "By Air: Fly to Chengdu, then continue overland (no closer airport exists). By Road: From Chengdu, buses to Moxi Town (base of Hailuogou) depart from Xinnanmen Station and take 6-7 hours (CNY 120-150); the new Ya'an-Kangding expressway plus the Luding-Moxi road cuts a private-car journey to about 5 hours. From Kangding, Moxi is 2 hours via the Luding junction. Getting Up: From Moxi (1,600m), park shuttle buses (CNY 90 round trip) climb the mountain road to Camp 3 (2,940m) in about 40 minutes, with dramatic views of the glacier tongue. The cable car (CNY 150 round trip) rises from Camp 3 to the Glacier Platform at 3,600m in 18 minutes, where boardwalks reach the glacier observation points. Entry Fee: CNY 90 (park) plus shuttle and cable car. The glacier terminus currently sits around 2,850m. Hailuogou pairs naturally with Gongga viewing or a night at the Moxi hot springs.",
    faqs: [
      { q: "Can I walk on the glacier?", a: "Yes. From Camp 3 a trail leads to the glacier surface at 2,850m. Guided walks with crampons available. Sturdy boots essential." },
      { q: "Are the hot springs natural?", a: "Yes, geothermally heated. Multiple outdoor pools at 38-42 C with mountain views. Night soaking with stars and snow peaks is the signature experience." },
      { q: "What is the best time to visit Hailuogou?", a: "October to February offers the clearest glacier views and the best hot-spring weather; the cable car runs year-round unless heavy snow closes it. Spring (April-May) brings rhododendron blooms on the slopes. June-September is monsoon season — the peak is often hidden, though the glacier itself remains impressive in the rain." },
      { q: "Is Hailuogou the same as Mount Gongga?", a: "Not exactly — Hailuogou is the glacier park on the eastern flank of Mount Gongga (7,556m). It is the most accessible way to experience Gongga's scale without trekking: the cable car puts you at 3,600m facing the mountain's east face and one of the lowest glaciers in Asia." },
      { q: "How difficult is the visit?", a: "Easy — shuttle buses and the cable car do the work, leaving short boardwalks at the glacier platform. Suitable for all ages. The only considerations are altitude (up to 3,600m — go slowly) and weather (the platform is 15 C colder than Moxi). Walking on the glacier itself requires a guide and proper boots." }
    ]
  }
};

const MAP = {
  meili_snow_mountain: "meili-snow",
  haba_snow_mountain: "haba-snow",
  namcha_barwa: "namcha-barwa",
  hengshan_hunan: "hengshan-hunan",
  hengshan_shanxi: "hengshan-shanxi",
  jade_dragon: "jade-dragon"
};

let updated = 0;
for (const [key, upgrade] of Object.entries(UPGRADES)) {
  const id = MAP[key] || key;
  const m = data.mountains.find((x) => x.id === id);
  if (!m) { console.error("NOT FOUND:", id); continue; }
  if (upgrade.whenToGo) m.whenToGo = upgrade.whenToGo;
  if (upgrade.howToGetThere) m.howToGetThere = upgrade.howToGetThere;
  if (upgrade.faqs) m.faqs = upgrade.faqs;
  updated++;
}

writeFileSync(dataPath, JSON.stringify(data, null, 2) + "\n", "utf-8");
console.log("Updated", updated, "mountains");
